https:
  port: "8082"
  
keystore:
  path: "docker01.domain.local.jks"
  password: "Welcome1"

sysProductAPI:
  forMySQL:
    host: "localhost"
    port: "443"
    
api:
  autodiscovery: "15524323"
  
anypoint:
  platform:
    client_id: "37022508df994929960b76d87e7f218b"
    client_secret: "4B9d1974C6fD4F2c8CD1360f1298575F"
    visualizer:
      layer: Domain