#%RAML 1.0
title: Product API
baseUri: https://mocksvc.mulesoft.com/mocks/48c0df7a-77c6-4b84-8d60-a93ce6bc8d41/{version} # baseUri: https://mocksvc.mulesoft.com/mocks/c8d0bf7b-966a-4b08-9dbc-0bb21d5fe36a/{version} # baseUri: https://mocksvc.mulesoft.com/mocks/bfc3f850-2465-49ce-b712-7f3701c44646/{version} # baseUri: http://localhost/{version}
version: v3
mediaType: [application/json, application/xml]
securedBy: [passthrough]
securitySchemes: 
  passthrough: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/pass-through-security-scheme/1.0.0/pass-through-security-scheme.raml

description: This API spec design highlights the power of RAML. It reuses existing RAML fragments for dataTypes, traits, resourceTypes and more to simplify and accelerate definig an API Spec. Fragments also ENSURE CONSISTENCY acrosss APIs. With consistency comes acclerated delivery due to developers familiarity with the design fragments. Overlays and extensions are available if needed to modify the API fragments.  \nRAML allows you to define RAML DataTypes and RAML NamedExamples instead of defining a schema and example for JSON and another for schema and example for XML and then trying to keep them in sync. With RAML DataTypes and NamedExamples you can support JSON & XML from one DataType and one NamedExample.

uses: 
  product: /exchange_modules/4ff02cd7-9e08-481b-890b-15ff7467b894/product-library/1.0.13/product-library.raml
  collectionRT: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/collection-library/1.0.30/collection-library.raml

/products:
  displayName: Products
  type:  
    collectionRT.collection:
  get:
    description: Retrieve all the Products.
    queryParameters: 
      productName?: 
        minLength: 3
        displayName: Product Name
      customerId?:
        displayName: Customer Id
        minLength: 3
      category?:
        displayName: Product Category
        minLength: 3
  post:
  /{id}:
    displayName: Product ID
    description: Get Product by ID
    type: 
      collectionRT.member:
    uriParameters: 
      id:
        example: "1"
        default: "1"
    get:
    put:
    delete:
